name: get_storage
description: Fast, lightweight synchronous key-value storage for Flutter with native, web, and WebAssembly support.
version: 2.2.0
homepage: https://github.com/devs-flutter-plugin/get_storage
repository: https://github.com/devs-flutter-plugin/get_storage
issue_tracker: https://github.com/devs-flutter-plugin/get_storage/issues

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  path_provider: ^2.1.6
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
